import
{
    Routes
}
from '@angular/router';

export const accountsFiananceRoutes:
    Routes =
[
    //===========================================================
    // Module Routes
    //===========================================================
    // Auto-generated by Module Synchronization Engine.
    // Future synchronization engines will register:
    //   • Menu routes
    //   • Submenu routes
    //   • Activity/Page routes
    //===========================================================

    //===========================================================
    // Default
    //===========================================================

    {
        path:'',

        redirectTo:'',

        pathMatch:'full'
    },
    // AUTO-BEGIN : MNU-007-001

    //===========================================================
    // Account Class
    //===========================================================

    {
        path:'account-class',

        data:
        {
            breadcrumb:'Account Class'
        },

        loadChildren:() =>
            import(
                '../account-class/routes/account-class.routes'
            )
            .then(
                m =>
                    m.mnu007001Routes
            )
    },

    // AUTO-END : MNU-007-001

];