import
{
    Routes
}
from '@angular/router';

//===========================================================
// MNU-002-007 Routes
//===========================================================

export const mnu002007Routes:
Routes =
[

    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================

    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-002-007-001

                //===========================================================
                // Default DB Components
                //===========================================================

                {
                    path:'default-db-components',

                    data:
                    {
                        breadcrumb:'Default DB Components'
                    },

                    loadChildren:() =>
                        import(
                            './default-db-components.routes'
                        )
                        .then(
                            m =>
                                m.DefaultDbComponentsRoutes
                        )
                },

                // AUTO-END : SUB-002-007-001

            // AUTO-BEGIN : SUB-002-007-002

                //===========================================================
                // Role Based DB Components
                //===========================================================

                {
                    path:'role-based-db-components',

                    data:
                    {
                        breadcrumb:'Role Based DB Components'
                    },

                    loadChildren:() =>
                        import(
                            './role-based-db-components.routes'
                        )
                        .then(
                            m =>
                                m.RoleBasedDbComponentsRoutes
                        )
                },

                // AUTO-END : SUB-002-007-002

        ]

    }

];