import
{
    Routes
}
from '@angular/router';


export const accountsFinanceRoutes:
    Routes =
[
    //===========================================================
    // Module Routes
    //===========================================================
    // Auto-generated by Module Synchronization Engine.
    // Future synchronization engines will register:
    //   • Menu routes
    //   • Submenu routes
    //   • Activity/Page routes
    //===========================================================


    //===========================================================
    // Default
    //===========================================================

    {
        path:'',

        redirectTo:'',

        pathMatch:'full'
    },
    // AUTO-BEGIN : MNU-007-001

    //===========================================================
    // Voucher Management
    //===========================================================

    {
        path:'voucher-management',

        data:
        {
            breadcrumb:'Voucher Management'
        },

        loadChildren:() =>
            import(
                '../voucher-management/routes/voucher-management.routes'
            )
            .then(
                m =>
                    m.mnu007001Routes
            )
    },

    // AUTO-END : MNU-007-001

];