import
{
    Routes
}
from '@angular/router';


export const securityPermissionRoutes:
    Routes =
[
    //===========================================================
    // Module Routes
    //===========================================================
    // Auto-generated by Module Synchronization Engine.
    // Future synchronization engines will register:
    //   • Menu routes
    //   • Submenu routes
    //   • Activity/Page routes
    //===========================================================


    //===========================================================
    // Default
    //===========================================================

    {
        path:'',

        redirectTo:'',

        pathMatch:'full'
    },
    // AUTO-BEGIN : MNU-006-001

    //===========================================================
    // Role Management
    //===========================================================

    {
        path:'role-management',

        data:
        {
            breadcrumb:'Role Management'
        },

        loadChildren:() =>
            import(
                '../role-management/routes/role-management.routes'
            )
            .then(
                m =>
                    m.mnu006001Routes
            )
    },

    // AUTO-END : MNU-006-001

];