import
{
    Routes
}
from '@angular/router';


//===========================================================
// MNU-005-001 Routes
//===========================================================

export const mnu005001Routes:
Routes =
[


    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================


    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-005-001-001

                //===========================================================
                // Department
                //===========================================================

                {
                    path:'department',

                    data:
                    {
                        breadcrumb:'Department'
                    },

                    loadChildren:() =>
                        import(
                            './department.routes'
                        )
                        .then(
                            m =>
                                m.DepartmentRoutes
                        )
                },

                // AUTO-END : SUB-005-001-001

            // AUTO-BEGIN : SUB-005-001-002

                //===========================================================
                // Designation
                //===========================================================

                {
                    path:'designation',

                    data:
                    {
                        breadcrumb:'Designation'
                    },

                    loadChildren:() =>
                        import(
                            './designation.routes'
                        )
                        .then(
                            m =>
                                m.DesignationRoutes
                        )
                },

                // AUTO-END : SUB-005-001-002

        ]

    }

];