using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AppCore.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class UpdateControlComponents : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "ControlComponents"
                ALTER COLUMN "id"
                ADD GENERATED BY DEFAULT AS IDENTITY;
                """
            );

            migrationBuilder.Sql(
                """
                SELECT setval(
                    pg_get_serial_sequence('"ControlComponents"', 'id'),
                    COALESCE(
                        (
                            SELECT MAX("id")
                            FROM "ControlComponents"
                        ),
                        1
                    ),
                    true
                );
                """
            );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "ControlComponents"
                ALTER COLUMN "id"
                DROP IDENTITY IF EXISTS;
                """
            );
        }
    }
}