import
{
    Routes
}
from '@angular/router';


//===========================================================
// MNU-002-004 Routes
//===========================================================

export const mnu002004Routes:
Routes =
[


    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================


    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-002-004-001

                //===========================================================
                // Source Control
                //===========================================================

                {
                    path:'source-control',

                    data:
                    {
                        breadcrumb:'Source Control'
                    },

                    loadChildren:() =>
                        import(
                            './source-control.routes'
                        )
                        .then(
                            m =>
                                m.SourceControlRoutes
                        )
                },

                // AUTO-END : SUB-002-004-001

        ]

    }

];