import
{
    Routes
}
from '@angular/router';


//===========================================================
// MNU-006-001 Routes
//===========================================================

export const mnu006001Routes:
Routes =
[


    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================


    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-006-001-001

                //===========================================================
                // Role Profile
                //===========================================================

                {
                    path:'role-profile',

                    data:
                    {
                        breadcrumb:'Role Profile'
                    },

                    loadChildren:() =>
                        import(
                            './role-profile.routes'
                        )
                        .then(
                            m =>
                                m.RoleProfileRoutes
                        )
                },

                // AUTO-END : SUB-006-001-001

            // AUTO-BEGIN : SUB-006-001-002

                //===========================================================
                // Activity Assignment
                //===========================================================

                {
                    path:'activity-assignment',

                    data:
                    {
                        breadcrumb:'Activity Assignment'
                    },

                    loadChildren:() =>
                        import(
                            './activity-assignment.routes'
                        )
                        .then(
                            m =>
                                m.ActivityAssignmentRoutes
                        )
                },

                // AUTO-END : SUB-006-001-002

        ]

    }

];