import
{
    Routes
}
from '@angular/router';


export const humanResourceManangementRoutes:
    Routes =
[
    //===========================================================
    // Module Routes
    //===========================================================
    // Auto-generated by Module Synchronization Engine.
    // Future synchronization engines will register:
    //   • Menu routes
    //   • Submenu routes
    //   • Activity/Page routes
    //===========================================================


    //===========================================================
    // Default
    //===========================================================

    {
        path:'',

        redirectTo:'',

        pathMatch:'full'
    },
    // AUTO-BEGIN : MNU-005-001

    //===========================================================
    // Human Resource Setup
    //===========================================================

    {
        path:'human-resource-setup',

        data:
        {
            breadcrumb:'Human Resource Setup'
        },

        loadChildren:() =>
            import(
                '../human-resource-setup/routes/human-resource-setup.routes'
            )
            .then(
                m =>
                    m.mnu005001Routes
            )
    },

    // AUTO-END : MNU-005-001

];