import
{
    Routes
}
from '@angular/router';


//===========================================================
// MNU-006-002 Routes
//===========================================================

export const mnu006002Routes:
Routes =
[


    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================


    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-006-002-004

                //===========================================================
                // Branch Assignment
                //===========================================================

                {
                    path:'branch-assignment',

                    data:
                    {
                        breadcrumb:'Branch Assignment'
                    },

                    loadChildren:() =>
                        import(
                            './branch-assignment.routes'
                        )
                        .then(
                            m =>
                                m.BranchAssignmentRoutes
                        )
                },

                // AUTO-END : SUB-006-002-004

            // AUTO-BEGIN : SUB-006-002-002

                //===========================================================
                // Role Assignment
                //===========================================================

                {
                    path:'role-assignment',

                    data:
                    {
                        breadcrumb:'Role Assignment'
                    },

                    loadChildren:() =>
                        import(
                            './role-assignment.routes'
                        )
                        .then(
                            m =>
                                m.RoleAssignmentRoutes
                        )
                },

                // AUTO-END : SUB-006-002-002

            // AUTO-BEGIN : SUB-006-002-003

                //===========================================================
                // Special Assignment
                //===========================================================

                {
                    path:'special-assignment',

                    data:
                    {
                        breadcrumb:'Special Assignment'
                    },

                    loadChildren:() =>
                        import(
                            './special-assignment.routes'
                        )
                        .then(
                            m =>
                                m.SpecialAssignmentRoutes
                        )
                },

                // AUTO-END : SUB-006-002-003

            // AUTO-BEGIN : SUB-006-002-001

                //===========================================================
                // User Profile
                //===========================================================

                {
                    path:'user-profile',

                    data:
                    {
                        breadcrumb:'User Profile'
                    },

                    loadChildren:() =>
                        import(
                            './user-profile.routes'
                        )
                        .then(
                            m =>
                                m.UserProfileRoutes
                        )
                },

                // AUTO-END : SUB-006-002-001

        ]

    }

];