import
{
    Routes
}
from '@angular/router';

//===========================================================
// MNU-003-001 Routes
//===========================================================

export const mnu003001Routes:
Routes =
[

    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================

    {
        path:'',

        children:
        [

            // AUTO-BEGIN : SUB-003-001-001

                //===========================================================
                // Company
                //===========================================================

                {
                    path:'company',

                    data:
                    {
                        breadcrumb:'Company'
                    },

                    loadChildren:() =>
                        import(
                            './company.routes'
                        )
                        .then(
                            m =>
                                m.CompanyRoutes
                        )
                },

                // AUTO-END : SUB-003-001-001

            // AUTO-BEGIN : SUB-003-001-002

                //===========================================================
                // Wings
                //===========================================================

                {
                    path:'wings',

                    data:
                    {
                        breadcrumb:'Wings'
                    },

                    loadChildren:() =>
                        import(
                            './wings.routes'
                        )
                        .then(
                            m =>
                                m.WingsRoutes
                        )
                },

                // AUTO-END : SUB-003-001-002

            // AUTO-BEGIN : SUB-003-001-003

                //===========================================================
                // Branches
                //===========================================================

                {
                    path:'branches',

                    data:
                    {
                        breadcrumb:'Branches'
                    },

                    loadChildren:() =>
                        import(
                            './branches.routes'
                        )
                        .then(
                            m =>
                                m.BranchesRoutes
                        )
                },

                // AUTO-END : SUB-003-001-003

            // AUTO-BEGIN : SUB-003-001-004

                //===========================================================
                // Warehouses
                //===========================================================

                {
                    path:'warehouses',

                    data:
                    {
                        breadcrumb:'Warehouses'
                    },

                    loadChildren:() =>
                        import(
                            './warehouses.routes'
                        )
                        .then(
                            m =>
                                m.WarehousesRoutes
                        )
                },

                // AUTO-END : SUB-003-001-004

            // AUTO-BEGIN : SUB-003-001-006

                //===========================================================
                // Financial Years
                //===========================================================

                {
                    path:'financial-years',

                    data:
                    {
                        breadcrumb:'Financial Years'
                    },

                    loadChildren:() =>
                        import(
                            './financial-years.routes'
                        )
                        .then(
                            m =>
                                m.FinancialYearsRoutes
                        )
                },

                // AUTO-END : SUB-003-001-006

            // AUTO-BEGIN : SUB-003-001-005

                //===========================================================
                // System Configurations
                //===========================================================

                {
                    path:'system-configurations',

                    data:
                    {
                        breadcrumb:'System Configurations'
                    },

                    loadChildren:() =>
                        import(
                            './system-configurations.routes'
                        )
                        .then(
                            m =>
                                m.SystemConfigurationsRoutes
                        )
                },

                // AUTO-END : SUB-003-001-005

        ]

    }

];