import
{
    Routes
}
from '@angular/router';


//===========================================================
// MNU-003-001 Routes
//===========================================================

export const mnu003001Routes:
Routes =
[


    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================


    {
        path:'',

        children:
        [

                // AUTO-BEGIN : SUB-003-001-001

    //===========================================================
    // Company
    //===========================================================

    {
        path:'company',

        data:
        {
            breadcrumb:'Company'
        },

        loadChildren:() =>
            import(
                './company.routes'
            )
            .then(
                m =>
                    m.CompanyRoutes
            )
    },

    // AUTO-END : SUB-003-001-001

// AUTO-BEGIN : SUB-003-001-002

    //===========================================================
    // Branch
    //===========================================================

    {
        path:'branch',

        data:
        {
            breadcrumb:'Branch'
        },

        loadChildren:() =>
            import(
                './branch.routes'
            )
            .then(
                m =>
                    m.BranchRoutes
            )
    },

    // AUTO-END : SUB-003-001-002

]

    }

];