import
{
    Routes
}
from '@angular/router';

//===========================================================
// MNU-002-003 Routes
//===========================================================

export const mnu002003Routes:
Routes =
[

    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================

    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-002-003-001

                //===========================================================
                // Control Components
                //===========================================================

                {
                    path:'control-components',

                    data:
                    {
                        breadcrumb:'Control Components'
                    },

                    loadChildren:() =>
                        import(
                            './control-components.routes'
                        )
                        .then(
                            m =>
                                m.ControlComponentsRoutes
                        )
                },

                // AUTO-END : SUB-002-003-001

            // AUTO-BEGIN : SUB-002-003-002

                //===========================================================
                // Layout Components
                //===========================================================

                {
                    path:'layout-components',

                    data:
                    {
                        breadcrumb:'Layout Components'
                    },

                    loadChildren:() =>
                        import(
                            './layout-components.routes'
                        )
                        .then(
                            m =>
                                m.LayoutComponentsRoutes
                        )
                },

                // AUTO-END : SUB-002-003-002

            // AUTO-BEGIN : SUB-002-003-003

                //===========================================================
                // Utility Components
                //===========================================================

                {
                    path:'utility-components',

                    data:
                    {
                        breadcrumb:'Utility Components'
                    },

                    loadChildren:() =>
                        import(
                            './utility-components.routes'
                        )
                        .then(
                            m =>
                                m.UtilityComponentsRoutes
                        )
                },

                // AUTO-END : SUB-002-003-003

        ]

    }

];