import
{
    Routes
}
from '@angular/router';


//===========================================================
// MNU-003-003 Routes
//===========================================================

export const mnu003003Routes:
Routes =
[


    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================


    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-003-003-001

                //===========================================================
                // Product Category
                //===========================================================

                {
                    path:'product-category',

                    data:
                    {
                        breadcrumb:'Product Category'
                    },

                    loadChildren:() =>
                        import(
                            './product-category.routes'
                        )
                        .then(
                            m =>
                                m.ProductCategoryRoutes
                        )
                },

                // AUTO-END : SUB-003-003-001

            // AUTO-BEGIN : SUB-003-003-003

                //===========================================================
                // Product Master
                //===========================================================

                {
                    path:'product-master',

                    data:
                    {
                        breadcrumb:'Product Master'
                    },

                    loadChildren:() =>
                        import(
                            './product-master.routes'
                        )
                        .then(
                            m =>
                                m.ProductMasterRoutes
                        )
                },

                // AUTO-END : SUB-003-003-003

            // AUTO-BEGIN : SUB-003-003-002

                //===========================================================
                // Product Sub Category
                //===========================================================

                {
                    path:'product-sub-category',

                    data:
                    {
                        breadcrumb:'Product Sub Category'
                    },

                    loadChildren:() =>
                        import(
                            './product-sub-category.routes'
                        )
                        .then(
                            m =>
                                m.ProductSubCategoryRoutes
                        )
                },

                // AUTO-END : SUB-003-003-002

        ]

    }

];