import
{
    Routes
}
from '@angular/router';


//===========================================================
// MNU-003-002 Routes
//===========================================================

export const mnu003002Routes:
Routes =
[


    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================


    {
        path:'',

        children:
        [

]

    }

];