import
{
    Routes
}
from '@angular/router';


//===========================================================
// MNU-002-005 Routes
//===========================================================

export const mnu002005Routes:
Routes =
[


    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================


    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-002-005-001

                //===========================================================
                // Login Pages
                //===========================================================

                {
                    path:'login-pages',

                    data:
                    {
                        breadcrumb:'Login Pages'
                    },

                    loadChildren:() =>
                        import(
                            './login-pages.routes'
                        )
                        .then(
                            m =>
                                m.LoginPagesRoutes
                        )
                },

                // AUTO-END : SUB-002-005-001

        ]

    }

];