import
{
Routes
}
from '@angular/router';


//===========================================================
// MNU-007-001 Routes
//===========================================================

export const mnu007001Routes:
Routes =
[


//===========================================================
// Menu Routes
//===========================================================
// Auto-generated by Menu Synchronization Engine.
// Submenu Synchronization Engine will register:
//   • Submenu routes
//   • Activity routes
//   • Page routes
//===========================================================


{
    path:'',

    children:
    [

        // SUBMENU ROUTE PLACEHOLDER

    ]

}

];