import
{
    Routes
}
from '@angular/router';


export const settingsRoutes:
    Routes =
[
    //===========================================================
    // Module Routes
    //===========================================================
    // Auto-generated by Module Synchronization Engine.
    // Future synchronization engines will register:
    //   • Menu routes
    //   • Submenu routes
    //   • Activity/Page routes
    //===========================================================


    //===========================================================
    // Default
    //===========================================================

    {
        path:'',

        redirectTo:'',

        pathMatch:'full'
    },
    // AUTO-BEGIN : MNU-005-001

    //===========================================================
    // General Settings
    //===========================================================

    {
        path:'general-settings',

        data:
        {
            breadcrumb:'General Settings'
        },

        loadChildren:() =>
            import(
                '../general-settings/routes/general-settings.routes'
            )
            .then(
                m =>
                    m.mnu005001Routes
            )
    },

    // AUTO-END : MNU-005-001

    // AUTO-BEGIN : MNU-005-002

    //===========================================================
    // Account Settings
    //===========================================================

    {
        path:'account-settings',

        data:
        {
            breadcrumb:'Account Settings'
        },

        loadChildren:() =>
            import(
                '../account-settings/routes/account-settings.routes'
            )
            .then(
                m =>
                    m.mnu005002Routes
            )
    },

    // AUTO-END : MNU-005-002

];