import
{
    Routes
}
from '@angular/router';


//===========================================================
// MNU-002-006 Routes
//===========================================================

export const mnu002006Routes:
Routes =
[


    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================


    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-002-006-001

                //===========================================================
                // Login Component 1
                //===========================================================

                {
                    path:'login-component-1',

                    data:
                    {
                        breadcrumb:'Login Component 1'
                    },

                    loadChildren:() =>
                        import(
                            './login-component-1.routes'
                        )
                        .then(
                            m =>
                                m.LoginComponent1Routes
                        )
                },

                // AUTO-END : SUB-002-006-001

            // AUTO-BEGIN : SUB-002-006-002

                //===========================================================
                // Login Component 2
                //===========================================================

                {
                    path:'login-component-2',

                    data:
                    {
                        breadcrumb:'Login Component 2'
                    },

                    loadChildren:() =>
                        import(
                            './login-component-2.routes'
                        )
                        .then(
                            m =>
                                m.LoginComponent2Routes
                        )
                },

                // AUTO-END : SUB-002-006-002

            // AUTO-BEGIN : SUB-002-006-003

                //===========================================================
                // Login Component 3
                //===========================================================

                {
                    path:'login-component-3',

                    data:
                    {
                        breadcrumb:'Login Component 3'
                    },

                    loadChildren:() =>
                        import(
                            './login-component-3.routes'
                        )
                        .then(
                            m =>
                                m.LoginComponent3Routes
                        )
                },

                // AUTO-END : SUB-002-006-003

            // AUTO-BEGIN : SUB-002-006-004

                //===========================================================
                // Login Component 4
                //===========================================================

                {
                    path:'login-component-4',

                    data:
                    {
                        breadcrumb:'Login Component 4'
                    },

                    loadChildren:() =>
                        import(
                            './login-component-4.routes'
                        )
                        .then(
                            m =>
                                m.LoginComponent4Routes
                        )
                },

                // AUTO-END : SUB-002-006-004

        ]

    }

];