import
{
    Routes
}
from '@angular/router';

//===========================================================
// MNU-002-006 Routes
//===========================================================

export const mnu002006Routes:
Routes =
[

    //===========================================================
    // Menu Routes
    //===========================================================
    // Auto-generated by Menu Synchronization Engine.
    // Submenu Synchronization Engine will register:
    //   • Submenu routes
    //   • Activity routes
    //   • Page routes
    //===========================================================

    {
        path:'',

        children:
        [

            // SUBMENU ROUTE PLACEHOLDER

            // AUTO-BEGIN : SUB-002-006-001

                //===========================================================
                // Core Components
                //===========================================================

                {
                    path:'core-components',

                    data:
                    {
                        breadcrumb:'Core Components'
                    },

                    loadChildren:() =>
                        import(
                            './core-components.routes'
                        )
                        .then(
                            m =>
                                m.CoreComponentsRoutes
                        )
                },

                // AUTO-END : SUB-002-006-001

            // AUTO-BEGIN : SUB-002-006-002

                //===========================================================
                // Sub Ordinate Components
                //===========================================================

                {
                    path:'sub-ordinate-components',

                    data:
                    {
                        breadcrumb:'Sub Ordinate Components'
                    },

                    loadChildren:() =>
                        import(
                            './sub-ordinate-components.routes'
                        )
                        .then(
                            m =>
                                m.SubOrdinateComponentsRoutes
                        )
                },

                // AUTO-END : SUB-002-006-002

        ]

    }

];