import
{
    Routes
}
from '@angular/router';


export const accountsFinanceRoutes:
    Routes =
[
    //===========================================================
    // Module Routes
    //===========================================================
    // Auto-generated by Module Synchronization Engine.
    // Future synchronization engines will register:
    //   • Menu routes
    //   • Submenu routes
    //   • Activity/Page routes
    //===========================================================


    //===========================================================
    // Default
    //===========================================================

    {
        path:'',

        redirectTo:'',

        pathMatch:'full'
    }
];